excluded:
  - '**/.build'
  - .build
  - .derivedData
  - vendor

disabled_rules:
  - closure_parameter_position
  - cyclomatic_complexity
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - identifier_name
  - inclusive_language
  - large_tuple
  - line_length
  - multiple_closures_with_trailing_closure
  - nesting
  - optional_data_string_conversion
  - redundant_discardable_let
  - type_body_length
  - vertical_parameter_alignment

reporter: xcode
